version: '3'

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres-swapping-books
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - backend-dev
  
  backend:
    platform: linux/amd64
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8002 --log-config log.ini --reload"
    build: .
    container_name: backend-swapping-books
    restart: always
    ports:
        - "8002:8002"
    volumes:
      - .:/app
    networks:
        - backend-dev
    depends_on:
        postgres:
          condition: service_healthy

networks:
    backend-dev:
        driver: bridge