"""index

Revision ID: 6be9784d1d86
Revises: 034481c5a10a
Create Date: 2023-11-15 09:39:28.307531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be9784d1d86'
down_revision = '034481c5a10a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_index(op.f('ix_books_name'), 'books', ['name'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_books_name'), table_name='books')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    # ### end Alembic commands ###
